class Core {
  // C++: enum BorderTypes
  static final int
  BORDER_CONSTANT = 0,
      BORDER_REPLICATE = 1,
      BORDER_REFLECT = 2,
      BORDER_WRAP = 3,
      BORDER_REFLECT_101 = 4,
      BORDER_TRANSPARENT = 5,
      BORDER_REFLECT101 = BORDER_REFLECT_101,
      BORDER_DEFAULT = BORDER_REFLECT_101,
      BORDER_ISOLATED = 16;
}